from enum import StrEnum


class NameOfSheet(StrEnum):
    Stocks = "stocks"
    StocksHard = "stocks_hard"
    StocksFBS = "stocks_FBS"
    Orders1Month = "orders_1mnth"
    Orders1Week = "orders_1week"
    Orders2Days = "orders_2days"
    OrdersToday = "orders_today"
    OrdersAlt = "orders_alt"
    StoragePaid = "storage_paid"
    TariffsBoxes = "tariffs_boxes"
    TariffsPallet = "tariffs_pallet"
    Statements = "statements"
    RK = "rk"
    Prices = "prices"
    FixedPrices = "fixed_prices"
    Coefficients = "coefficients"
    Sales1Month = "sales_1mnth"
    SalesToday = "sales_today"
    Analytics = "analytics"
    ProductsWB = "productsWB"
    ProductsMP = "productsMP"
    Products = "products"
    StockOnWarehouse = "stock_on_warehouse"
    Sendings = "sendings"
    Statistics = "statistics"
    StatisticsProduct = "statistics_product"
    CardsList = "cards_list"
