import schedule
from Api import Api


def WB_cycle():
    API = Api()
    # Утро гранд
    schedule.every().day.at("01:45").do(API.start, 'stocks', 'grand', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("01:50").do(API.start, 'orders_1mnth', 'grand', 'WB', dateFrom='1mnth')
    schedule.every().day.at("01:55").do(API.start, 'orders_1week', 'grand', 'WB', dateFrom='1week')
    schedule.every().day.at("02:00").do(API.start, 'orders_2days', 'grand', 'WB', dateFrom='2days')
    schedule.every().day.at("02:05").do(API.start, 'orders_today', 'grand', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("02:10").do(API.start, 'tariffs_boxes', 'grand', 'WB', date='tariffs')
    schedule.every().day.at("02:15").do(API.start, 'tariffs_pallet', 'grand', 'WB', date='tariffs')
    # День гранд
    schedule.every(30).minutes.do(API.start, 'prices', 'grand', 'WB', limit='1000')
    schedule.every().day.at("10:45").do(API.start, 'stocks', 'grand', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("10:50").do(API.start, 'orders_1mnth', 'grand', 'WB', dateFrom='1mnth')
    schedule.every().day.at("10:55").do(API.start, 'orders_1week', 'grand', 'WB', dateFrom='1week')
    schedule.every().day.at("11:00").do(API.start, 'orders_2days', 'grand', 'WB', dateFrom='2days')
    schedule.every().day.at("11:05").do(API.start, 'orders_today', 'grand', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("11:10").do(API.start, 'tariffs_boxes', 'grand', 'WB', date='tariffs')
    schedule.every().day.at("11:15").do(API.start, 'tariffs_pallet', 'grand', 'WB', date='tariffs')
    # Утро терехов
    schedule.every().day.at("02:45").do(API.start, 'stocks', 'terehov', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("02:50").do(API.start, 'orders_1mnth', 'terehov', 'WB', dateFrom='1mnth')
    schedule.every().day.at("02:55").do(API.start, 'orders_1week', 'terehov', 'WB', dateFrom='1week')
    schedule.every().day.at("03:00").do(API.start, 'orders_2days', 'terehov', 'WB', dateFrom='2days')
    schedule.every().day.at("03:05").do(API.start, 'orders_today', 'terehov', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("03:10").do(API.start, 'tariffs_boxes', 'terehov', 'WB', date='tariffs')
    schedule.every().day.at("03:15").do(API.start, 'tariffs_pallet', 'terehov', 'WB', date='tariffs')
    # День терехов
    schedule.every(30).minutes.do(API.start, 'prices', 'terehov', 'WB', limit='1000')
    schedule.every().day.at("11:45").do(API.start, 'stocks', 'terehov', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("11:50").do(API.start, 'orders_1mnth', 'terehov', 'WB', dateFrom='1mnth')
    schedule.every().day.at("11:55").do(API.start, 'orders_1week', 'terehov', 'WB', dateFrom='1week')
    schedule.every().day.at("12:00").do(API.start, 'orders_2days', 'terehov', 'WB', dateFrom='2days')
    schedule.every().day.at("12:05").do(API.start, 'orders_today', 'terehov', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("12:10").do(API.start, 'tariffs_boxes', 'terehov', 'WB', date='tariffs')
    schedule.every().day.at("12:15").do(API.start, 'tariffs_pallet', 'terehov', 'WB', date='tariffs')
    # Утро дкн
    schedule.every().day.at("03:45").do(API.start, 'stocks', 'dnk', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("03:50").do(API.start, 'orders_1mnth', 'dnk', 'WB', dateFrom='1mnth')
    schedule.every().day.at("03:55").do(API.start, 'orders_1week', 'dnk', 'WB', dateFrom='1week')
    schedule.every().day.at("04:00").do(API.start, 'orders_2days', 'dnk', 'WB', dateFrom='2days')
    schedule.every().day.at("04:05").do(API.start, 'orders_today', 'dnk', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("04:10").do(API.start, 'tariffs_boxes', 'dnk', 'WB', date='tariffs')
    schedule.every().day.at("04:15").do(API.start, 'tariffs_pallet', 'dnk', 'WB', date='tariffs')
    # День днк
    schedule.every(30).minutes.do(API.start, 'prices', 'dnk', 'WB', limit='1000')
    schedule.every().day.at("12:45").do(API.start, 'stocks', 'dnk', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("12:50").do(API.start, 'orders_1mnth', 'dnk', 'WB', dateFrom='1mnth')
    schedule.every().day.at("12:55").do(API.start, 'orders_1week', 'dnk', 'WB', dateFrom='1week')
    schedule.every().day.at("13:00").do(API.start, 'orders_2days', 'dnk', 'WB', dateFrom='2days')
    schedule.every().day.at("13:05").do(API.start, 'orders_today', 'dnk', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("13:10").do(API.start, 'tariffs_boxes', 'dnk', 'WB', date='tariffs')
    schedule.every().day.at("13:15").do(API.start, 'tariffs_pallet', 'dnk', 'WB', date='tariffs')
    # Утро планета
    schedule.every().day.at("04:45").do(API.start, 'stocks', 'planeta', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("04:50").do(API.start, 'orders_1mnth', 'planeta', 'WB', dateFrom='1mnth')
    schedule.every().day.at("04:55").do(API.start, 'orders_1week', 'planeta', 'WB', dateFrom='1week')
    schedule.every().day.at("05:00").do(API.start, 'orders_2days', 'planeta', 'WB', dateFrom='2days')
    schedule.every().day.at("05:05").do(API.start, 'orders_today', 'planeta', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("05:10").do(API.start, 'tariffs_boxes', 'planeta', 'WB', date='tariffs')
    schedule.every().day.at("05:15").do(API.start, 'tariffs_pallet', 'planeta', 'WB', date='tariffs')
    # День планета
    schedule.every(30).minutes.do(API.start, 'prices', 'planeta', 'WB', limit='1000')
    schedule.every().day.at("13:45").do(API.start, 'stocks', 'planeta', 'WB', dateFrom='2019-06-20')
    schedule.every().day.at("13:50").do(API.start, 'orders_1mnth', 'planeta', 'WB', dateFrom='1mnth')
    schedule.every().day.at("13:55").do(API.start, 'orders_1week', 'planeta', 'WB', dateFrom='1week')
    schedule.every().day.at("14:00").do(API.start, 'orders_2days', 'planeta', 'WB', dateFrom='2days')
    schedule.every().day.at("14:05").do(API.start, 'orders_today', 'planeta', 'WB', dateFrom='today', flag='1')
    schedule.every().day.at("14:10").do(API.start, 'tariffs_boxes', 'planeta', 'WB', date='tariffs')
    schedule.every().day.at("14:15").do(API.start, 'tariffs_pallet', 'planeta', 'WB', date='tariffs')